// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecjeovmpzxxpzhdtvkbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjamVvdm1wenh4cHpoZHR2a2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjQ3MDksImV4cCI6MjA3MDAwMDcwOX0.CqCI-qL5OY508q6Zq_0ZVUlTcXLpzZgtnFY6O2QVs6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});